// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPokerAdmin(ctx context.Context, arg *AddPokerAdminParams) (*PokerAdmin, error)
	AddPokerUser(ctx context.Context, arg *AddPokerUserParams) (*PokerUser, error)
	AddTask(ctx context.Context, arg *AddTaskParams) (*Task, error)
	AddUserAuthProviders(ctx context.Context, arg *AddUserAuthProvidersParams) (*UserAuthProvider, error)
	AddVoting(ctx context.Context, arg *AddVotingParams) (*Voting, error)
	ClearTasks(ctx context.Context, pokerID pgtype.UUID) error
	ClearVote(ctx context.Context, arg *ClearVoteParams) error
	CreateComent(ctx context.Context, arg *CreateComentParams) (int64, error)
	CreatePoker(ctx context.Context, arg *CreatePokerParams) (*Poker, error)
	CreateUser(ctx context.Context, name string) (int64, error)
	DeletePoker(ctx context.Context, pokerID pgtype.UUID) error
	DeletePokerAdmins(ctx context.Context, pokerID pgtype.UUID) error
	DeletePokerComments(ctx context.Context, pokerID pgtype.UUID) error
	DeletePokerTasks(ctx context.Context, pokerID pgtype.UUID) error
	DeletePokerUsers(ctx context.Context, pokerID pgtype.UUID) error
	DeletePokerVotings(ctx context.Context, pokerID pgtype.UUID) error
	DeleteTask(ctx context.Context, arg *DeleteTaskParams) error
	GetComments(ctx context.Context, arg *GetCommentsParams) ([]*Comment, error)
	GetLastSession(ctx context.Context, arg *GetLastSessionParams) ([]*GetLastSessionRow, error)
	GetPoker(ctx context.Context, pokerID pgtype.UUID) (*Poker, error)
	GetPokerAdmins(ctx context.Context, pokerID pgtype.UUID) ([]int64, error)
	GetTask(ctx context.Context, arg *GetTaskParams) (*Task, error)
	GetTasks(ctx context.Context, pokerID pgtype.UUID) ([]*Task, error)
	GetUserAuthProvidersByProviderUid(ctx context.Context, arg *GetUserAuthProvidersByProviderUidParams) (*UserAuthProvider, error)
	GetUserByID(ctx context.Context, userID int64) (*User, error)
	GetUserEstimate(ctx context.Context, arg *GetUserEstimateParams) (int32, error)
	GetUserIDsByPokerID(ctx context.Context, pokerID pgtype.UUID) ([]*PokerUser, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]*User, error)
	GetVotingResults(ctx context.Context, arg *GetVotingResultsParams) ([]*GetVotingResultsRow, error)
	GetVotingState(ctx context.Context, pokerID pgtype.UUID) (*GetVotingStateRow, error)
	RemoveVote(ctx context.Context, arg *RemoveVoteParams) error
	UpdatePokerTaskAndDates(ctx context.Context, arg *UpdatePokerTaskAndDatesParams) error
	UpdateTask(ctx context.Context, arg *UpdateTaskParams) (*Task, error)
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
	UpsertUserSettings(ctx context.Context, arg *UpsertUserSettingsParams) (*UserSetting, error)
}

var _ Querier = (*Queries)(nil)
